export const DELETE_NOTIFICATION = "DELETE_NOTIFICATION";

export const UPADTE_ITEM_COUNT_SHOPPING_CART = "UPADTE_ITEM_COUNT_SHOPPING_CART";

export const DELETE_ITEM_SHOPPING_CART = "DELETE_ITEM_SHOPPING_CART";

export const ADD_TO_SHOPPING_CART = "ADD_TO_SHOPPING_CART"; 

export const DELETE_WISHLIST = "DELETE_WISHLIST";

export const ADD_RATE = "ADD_RATE";

export const DELETE_PRODUCT = "DELETE_PRODUCT";